Repository Kim-Yeon-ho/2023_SoftwareEng01, pull requests merged in 2023-11, with the labels that each got.

#10 Stack 구현
  main.py
Labels: 전승혁

#9 main 함수 코드 작성
  main.py
Labels: 이주형

#15 계산기 함수 작성
  main.py
Labels: 김연호

#17 isDivision함수 작성
  main.py
Labels: 이인석

#13 정수 예외 처리 코드 작성
  .DS_Store
  main.py
Labels: 서정우

#18 이스터애그 함수정의, isequal 함수 출력 부분 수정
  main.py
Labels: 강지현
